# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: roger-vote:${VOTE_TAG:-dev}
    build: 
      context: ../../app/vote
      target: dev
    depends_on:
      redis:
        condition: service_healthy
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
     - ../../app/vote:/usr/local/app
    expose:
      - "80"
    networks:
      - front-tier
      - back-tier
  
  vote2:
      image: roger-vote2:${VOTE_TAG:-dev}
      build: 
        context: ../../app/vote
        target: dev
      depends_on:
        redis:
          condition: service_healthy
      healthcheck: 
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 15s
        timeout: 5s
        retries: 3
        start_period: 10s
      volumes:
      - ../../app/vote:/usr/local/app
      expose:
        - "80"
      networks:
        - front-tier
        - back-tier

  result:
    build: ../../app/result
    # use nodemon rather than node for local dev
    entrypoint: nodemon --inspect=0.0.0.0 server.js
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - ../../app/result:/usr/local/app
    expose:
      - "81"
    networks:
      - front-tier
      - back-tier
  
  result2:
    build: ../../app/result
    # use nodemon rather than node for local dev
    entrypoint: nodemon --inspect=0.0.0.0 server.js
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - ../../app/result:/usr/local/app
    expose:
      - "81"
    networks:
      - front-tier
      - back-tier


  worker:
    build:
      context: ../../app/worker
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - "../healthchecks:/healthchecks:ro"
    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/redis.sh"]
      interval: "5s"
      timeout: "3s"
      retries: 20
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "../healthchecks:/healthchecks:ro"
    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/postgres.sh"]
      interval: "5s"
      timeout: "5s"
      retries: 20
    networks:
      - back-tier

  # this service runs once to seed the database with votes
  # it won't run unless you specify the "seed" profile
  # docker compose --profile seed up -d
  seed:
    build: ../seed-data
    profiles: ["seed"]
    depends_on:
      vote:
        condition: service_healthy 
    networks:
      - front-tier
    restart: "no"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - vote
      - result
    networks:
      - front-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
